services:
  productservice:
    build:
      context: ../ECommerce.Products.API/Products.API
      dockerfile: Dockerfile
    restart: always
    container_name: productservice
    ports:
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8081
      - ConnectionStrings__DefaultConnection=Server=databaseserver,1433;Database=productdb;User Id=sa;Password=Verystrongpassword123;TrustServerCertificate=True;
      - Rabbitmq__Host=rabbitmq
      - Rabbitmq__Port=5672
      - Rabbitmq__Exchange=user
      - Rabbitmq__Username=guest
      - Rabbitmq__Password=guest
    depends_on:
      - database
      - rabbitmq
    networks:
      - shared-network

  authservice:
    build:
      context: ../ECommerce.AuthService/ECommerce.AuthService
      dockerfile: Dockerfile
    restart: always
    container_name: authservice
    ports:
      - "8082:8082"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8082
      - ConnectionStrings__DefaultConnection=Server=databaseserver,1433;Database=authdb;User Id=sa;Password=Verystrongpassword123;TrustServerCertificate=True;
      - Rabbitmq__Host=rabbitmq
      - Rabbitmq__Port=5672
      - Rabbitmq__Exchange=user
      - Rabbitmq__Username=guest
      - Rabbitmq__Password=guest
    depends_on:
      - database
      - rabbitmq
    networks:
      - shared-network

  orderservice:
    build:
      context: ../ECommerce.Order.API/ECommerce.Order.API
      dockerfile: Dockerfile
    restart: always
    container_name: orderservice
    ports:
      - "8083:8083"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8083
      - ConnectionStrings__DefaultConnection=Server=databaseserver,1433;Database=ordersdb;User Id=sa;Password=Verystrongpassword123;TrustServerCertificate=True;
      - Rabbitmq__Host=rabbitmq
      - Rabbitmq__Port=5672
      - Rabbitmq__Exchange=user
      - Rabbitmq__Username=guest
      - Rabbitmq__Password=guest
    depends_on:
      - database
      - rabbitmq
    networks:
      - shared-network

  database:
    container_name: database
    hostname: databaseserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Verystrongpassword123"
      MSSQL_DATA_DIR: /var/opt/mssql/data
      MSSQL_PID: "Developer"
      MSSQL_TCP_PORT: 1433
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - shared-network

  angular:
    build:
      context: ../ECommerce.WebApp.UI
      dockerfile: Dockerfile
    container_name: webapp-angular-container
    ports:
      - "88:80"
    depends_on:
      - productservice
      - authservice
      - orderservice
    networks:
      - shared-network

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - shared-network

volumes:
  mssql_data:
  rabbitmq_data:

networks:
  shared-network:
    driver: bridge
